Cluster name dynamic and used helm to deploy

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -9,13 +9,18 @@ on:
 
 permissions:
   contents: read
-  id-token: write
 
 jobs:
   deploy:
     if: github.event.workflow_run.conclusion == 'success'
 
     runs-on: ubuntu-latest
+
+    env:
+      CLUSTER_NAME: eks-production-cluster
+      NAMESPACE: production
+      RELEASE_NAME: my-app
+      CHART_PATH: ./helm/my-app
 
     steps:
       - name: Checkout code
@@ -27,14 +32,49 @@ jobs:
           aws-region: ${{ secrets.AWS_REGION }}
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          #role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+
+      - name: Download Terraform Outputs
+        uses: dawidd6/action-download-artifact@v6
+        with:
+          workflow: terraform.yml
+          name: terraform-outputs
+          path: .
+
+      - name: Read Cluster Name
+        run: |
+          CLUSTER_NAME=$(jq -r '.eks_cluster_name.value' terraform-output.json)
+         
+          if [ -z "$CLUSTER_NAME" ] || [ "$CLUSTER_NAME" = "null" ]; then
+          echo "Cluster name missing"
+          exit 1
+          fi
+
+          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
 
       - name: Configure kubectl
         run: |
           aws eks update-kubeconfig \
             --region ${{ secrets.AWS_REGION }} \
-            --name eks-production-cluster
+            --name $CLUSTER_NAME
 
-      - name: Deploy to EKS
+      - name: Install Helm
+        uses: azure/setup-helm@v4
+        with:
+          version: v3.15.2
+
+      - name: Verify Cluster Access
         run: |
-          kubectl apply -f k8s/
+          kubectl get nodes
+
+      - name: Deploy using Helm
+        run: |
+          helm upgrade --install $RELEASE_NAME $CHART_PATH \
+            --namespace $NAMESPACE \
+            --create-namespace \
+            --wait \
+            --atomic \
+            --timeout 10m
+
+      - name: Verify Deployment
+        run: |
+          kubectl get pods -n $NAMESPACE
